unsealer:
  metrics:
    enabled: false
vault:
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
                capabilities = ["read", "list", "delete", "create", "update"]
              }
      - name: read_secrets
        rules: path "secret/*" {
                capabilities = ["read", "list"]
              }
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: "default"
            bound_service_account_namespaces: "default"
            policies: allow_secrets
            ttl: 1h
          - name: atlantis
            bound_service_account_names: "atlantis"
            bound_service_account_namespaces: "atlantis"
            policies: read_secrets
            ttl: 1h
          - name: argo
            bound_service_account_names: "*"
            bound_service_account_namespaces: "argo"
            policies: read_secrets
            ttl: 1h
