apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
  name: build-go-app-sensor
  namespace: argo
spec:
  imagePullPolicy: Always
  imageVersion: latest
  repeat: true
  serviceAccountName: argo-events-sa
  signals:
  - name: webhook-gateway/github
  triggers:
  - name: argo-workflow
    resource:
      group: argoproj.io
      kind: Workflow
      version: v1alpha1
      namespace: argo
      parameters:
      - dest: spec.arguments.parameters.0.value
        src:
          path: head_commit.id
          signal: webhook-gateway/github
      - dest: spec.arguments.parameters.1.value
        src:
          path: repository.full_name
          signal: webhook-gateway/github
      source:
        url:
          path: "https://raw.githubusercontent.com/suntechsoft/infra-provisioning/develop/workflows/golang-github-push.yaml?token=AWpDUTafARamPwcx0-8vKLls3wK7fT14ks5cTkq8wA%3D%3D"
          verifycert: false
