{{- if .Values.argo.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo-vs
  namespace: argo
spec:
  hosts:
  - "{{ .Values.argo.host }}"
  gateways:
  - argo-gateway
  http:
  - route:
    - destination:
        port:
          number: 12000
        host: argo
{{- end -}}
