apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cloudflare-clear-cache-
spec:
  serviceAccountName: argo
  entrypoint: clear-cache
  templates:
  - name: clear-cache
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault-vault.vault.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-role: "argo"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    script:
      image: appropriate/curl
      command: [bash]
      source: |
        curl -X POST \
          -H "X-Auth-Key: $CLOUDFLARE_TOKEN" \
          -H "X-Auth-Email: a.nasinnyk@globalgames.com" \
          -H "Content-Type: application/json" \
          https://api.cloudflare.com/client/v4/zones/c063988ebffb9233d24e8b0cdd0f9cf2/purge_cache
      env:
      - name: CLOUDFLARE_TOKEN
        value: vault:secret/data/argo#CLOUDFLARE_TOKEN
