apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-vault-infra-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  {{- range $key, $value := .Values.vault.crb }}
- kind: ServiceAccount
  name: {{ $key }}
  namespace: {{ $value }}
  {{- end }}
