{{- if .Values.atlantis.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: atlantis-gateway
  namespace: atlantis
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: atlantis
      number: 80
      protocol: HTTP
    hosts:
    - "{{ .Values.atlantis.host }}"
{{- end -}}
